### ISSUE TITLE
UCOB Nael Quote(?) Bug

### ISSUE THREAD

**Issue by Datachange** [quisquous/cactbot#2830]
~~[5/2/2021~~ ~~7:25:39~~ ~~PM]~~ ~~Info:~~ ~~RaidbossAlerts:~~ ~~BrowserConsole:~~ ~~Uncaught~~ ~~(in~~ ~~promise)~~ ~~TypeError:~~ ~~Cannot~~ ~~read~~ ~~property~~ ~~'stack'~~ ~~of~~ ~~undefined~~ ~~(Source:~~ ~~file:///D:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/cactbot/dist/raidboss.bundle.js,~~ ~~Line:~~ ~~1)~~

~~I~~ ~~think~~ ~~this~~ ~~is~~ ~~a~~ ~~bug~~ ~~causing~~ ~~problems~~ ~~with~~ ~~the~~ ~~TTS~~ ~~for~~ ~~the~~ ~~Nael~~ ~~quotes.~~

At this point, something is just wrong with the Nael Quote's TTS. Literally every other callout works fine in UCOB.
Overriding the triggers to have a manual TTS function does not work, either.

**Comment by quisquous** [comment]
Was there anything else in the log? The lines before and after say which trigger this was as well as additional lines for the stack trace.

**Comment by Datachange** [comment]
When running in the emulator, there are no errors. The text alerts work just fine, but the TTS aspect isn't working.

**Comment by quisquous** [comment]
Does TTS work normally for you, such as the test triggers in Summerford Farms?

**Comment by Datachange** [comment]
We've had no issues with TTS with any other mechanic. Only the Nael Quotes.

**Comment by quisquous** [comment]
If this happens again, can you print the surrounding lines in the log?

**Comment by panicstevenson** [comment]
The error logging here should be erroneously logged (👀) from there not actually being an error when we reject the open promises from certain triggers; in this case, Nael quotes have a delaySeconds property, which would be one of these instances. This is addressed in https://github.com/quisquous/cactbot/pull/2837; please report back if you still see the error logs after whatever next release.

As for TTS not happening, that may or may not be completely unrelated.

**Comment by Datachange** [comment]
So, we cleared out the error log, removed any and all nael quote overridden triggers, and we don't get the error. However, we're still not seeing the nael quotes make it over TTS (while literally every other trigger works fine), so this error log should be rebranded as such.

**Comment by quisquous** [comment]
Hmm.  More questions:

What do you mean by "nael quote overridden triggers"?

Do you have "hide chat log for privacy" turned on in your ffxiv settings?

How are you turning on TTS? What do you mean by "every other trigger works fine"? Do you mean that TTS works for those triggers or those triggers show alert text?

**Comment by quisquous** [comment]
Also, feel free to attach a recent zipped up Network log file and I can take a look.

**Comment by Datachange** [comment]
Private chat was the problem. I am sorry. :(

**Comment by quisquous** [comment]
No need for apologies at all!  Thanks for confirming that was it!  Sorry this took so long to think of that possible idea.  I filed https://github.com/ravahn/FFXIV_ACT_Plugin/issues/264 to hopefully address this because this isn't the first time this (or things like this) have happened.
