### ISSUE TITLE
Certain "targeted" callouts and certain oopsy items missing when using alt character

### ISSUE THREAD

**Issue by wexxlee** [quisquous/cactbot#4117]
Over the last several weeks, I've noticed that certain cactbot callouts and certain items that should appear for me in Oopsy (missing a party member with my buff) are not appearing, but only when I'm in a fight on my alt character.  If I switch over to my main character and run the same fight, all callouts/oopsy seem to work just fine.  Specific things I've observed about this problem:
 - Affects the P3S Bright Fire Marker and Fledgling Flights mechanic -- on my alt, no alert text with the num is displayed, and no sound is played (works fine on main character)
 - Food buff not displayed in jobs when on my alt
 - Oopsy does not display when my buff (Embolden) misses party members on my alt (again, works fine on my main).

I'm pretty sure I've noticed in other fights where there is a "targeted" mechanic on me (as opposed to a general raid alert) that cactbot will not call out the mechanic if I am raiding on my alt.  I can't think of a specific example, but I'm happy to go do additional testing.

Behavior is reproducible when switching back and forth between accounts without closing/restarting the game or ACT.  Also reproducible when opening ACT fresh and loading into game on my alt with no prior activity on my main that day.

Not sure whether this is relevant, but there is another player in the raid when on my alt who has the same first name ("Wind-up") - although I do see alerts relevant to his character (e.g. in P1S, the Close: / Far: shackle alerts will call out his name).

Attaching the console error log from two nights ago that shows a number of errors when these problems were happening.
[cactbot-error-log-22.02.10.txt](https://github.com/quisquous/cactbot/files/8054638/cactbot-error-log-22.02.10.txt)

**Comment by quisquous** [comment]
These are all very strange behaviors.

Are you running multiple versions of ffxiv at the same time? Are you playing your alt in a different language? Does the cactbot test overlay work for your alt?

Re: same player in the raid with the first name.  You can add nicknames in your `user/raidboss.js` or `user/oopsyraidsy.js` files to use different names for the two of you: <https://github.com/quisquous/cactbot/blob/main/user/raidboss-example.js#L28-L33>.  Just conflicting first names should not cause any bigger issues.

Re: `Oopsy: BrowserConsole: Couldn't find name for 0000 (owner: 0000)` errors.  Those should be fixed now.

**Comment by wexxlee** [comment]
(1) No, only one version of FFXIV, and only one running at a time.
(2) No, same language for both characters.
(3) Test overlay works fine, as does the /cd test in Summerford Farms.  And cactbot does display most callouts on my alt, just not the bright fire numbers or fledgling flight direction placements in P3S -- basically, any callout unique to my character and not a general fight callout.  (I can run some other fights to verify).

It's definitely puzzling.  If you think I need to do a clean reinstall, I can.

**Comment by wexxlee** [comment]
Also noticed earlier tonight that it affects the Kampeos Harma alerts in P2S (i.e. I get the callout on my main, and not my alt), so it definitely seems to be affecting any "personalized" callouts.

**Comment by wexxlee** [comment]
@quisquous I did a complete uninstall/clean reinstall of ACT/OverlayPlugin/cactbot, and unfortunately, the problem is still happening.  Here are exact repro steps - I also have a log file that contains only these two encounters if it helps with repro:

1.  Log into main character.  Switch to tank (GNB).
2.  Run Eden's Gate: Resurrection Savage (E1S) using undersized party option (solo encounter)
3.  Start encounter.
4.  Alert/info messages are displayed correctly on screen.  Specifically:
   - "aoe" info message displayed for "E1S Eden's Gravity" event
   - "Puddle Spread" alert message displayed for "E1S Vice and Virtue" event
   - "Tank Buster on YOU" alert message displayed for "E1S Spear of Paradise" event
5. Wipe, leave encounter, log out.
6. Log in with alt character.  Switch to tank (GNB).
7. Run E1S using undersized party option (solo).
8. Start encounter.
9. Alert/info messages are only _**partially**_ displayed correctly on screen.  Specifically:
   - "aoe" info message **is** displayed for "E1S Vice and Virtue" event
   - **No** "Puddle Spread" alert message is displayed for "E1S Vice and Virtue" event
   - For "E1S Spear of Paradise" event, the alert message displayed is simply "Tank Buster" (not the specific alert indicative of a tank buster being on my character, even though it was.
10.  Wipe, leave encounter, log out.

Attached is the log file for these two encounters.
[cactbot_errorlog_issue_4117.log](https://github.com/quisquous/cactbot/files/8182495/cactbot_errorlog_issue_4117.log)

Some additional information, in case it's helpful:
- I had the Cactbot test overlay up for both fights.  It correctly identified my character, both on my main and on my alt.  The data in the overlay looked generally correct.
- I ran this encounter log through raidemulator.  It emulated the info/alert messages I *should* have received on my alt, not the ones I actually received.  Thus, it does not seem to reproduce the problematic behavior.  I was hoping this would show the issue, but since it doesn't, would an actual vod help?

I'm at a total loss - is there other debugging I can do?  Really appreciate your help.

**Comment by quisquous** [comment]
Do you know how to use devtools? On your alt, go into E1S.  Go into ACT -> Plugins -> OverlayPlugin.dll -> whatever you call raidboss alerts or combined -> Open DevTools.  From there in the window that pops up, click Sources.  Then open up the folders top/cactbot/./resources/responses.ts.  Ctrl+F for tankBusterSwap.  Then click on line 223 and 228 (the ones that say `const target = getTarget(matches);`).  Now start the fight, at some point when that mechanic happens, devtools will say `Paused in debugger` on your overlay.  Go back to the devtools window.  It'll look something like this:

![image](https://user-images.githubusercontent.com/462317/156688869-71b49fe9-be53-4514-b258-77ab1b655bdb.png)

Mostly I'm curious what the values of `data` and `matches` are in the right hand window.

**Comment by wexxlee** [comment]
@quisquous Not familiar with DevTools, but will do my best.  When I followed your instructions, I don't have the same tree of pages, and I wasn't able to add additional paths.  Here's what mine looks like, fully expanded: 
![image](https://user-images.githubusercontent.com/86693821/156907085-ce38f6b7-f2fc-48ac-a95a-30d8666c1299.png)

**Comment by quisquous** [comment]
Can you switch the url of your overlay to https://quisquous.github.io/cactbot/ui/raidboss/raidboss.html?timeline=0&alerts=1 and then try it again?

**Comment by wexxlee** [comment]
@quisquous Thanks, that seemed to work.  I got the 'Paused in debugger' message in the overlay - and here's the info from DevTools:
![image](https://user-images.githubusercontent.com/86693821/156907917-2f04aa96-035f-4d05-ab7a-60e64a5499e3.png)

**Comment by wexxlee** [comment]
Maybe a capitalization issue?  Looks like data.me has the "Up" part capitalized and matches.target has the "up" lowercase (which is how it's actually shown in-game):
![image](https://user-images.githubusercontent.com/86693821/156908704-d828edc7-dc90-4aac-8ab1-88dbd55a44a3.png)

**Comment by quisquous** [comment]
Thanks for the debugging! I suspect #4175 will fix the issue for you.  If you wanted to try it out before the next release, you can download the artifacts link at the bottom of https://github.com/quisquous/cactbot/actions/runs/1940492343#artifacts and replace your cactbot dlls with the two dlls in that zip file.

**Comment by wexxlee** [comment]
Works like a charm!  Thank you!
