### ISSUE TITLE
UCoB Issues (Stealth changes in Shadowbringers).  Not in patch notes.

### ISSUE THREAD

**Issue by dencur** [quisquous/cactbot#435]
Shadowbringers stealth changes. 

Cactbot no longer calculates Nael divebomb marker locations automatically.

Doom Puddles trigger twice sometimes with different counts.  Like it can say "Doom 1" followed immediately by "Doom 3", when it is actually a Doom 1.  Usually the first one is correct.

UCoB Nael quotes have changed. This is what we have so far.  Not sure if the rest can be mined.  If we get them I'll update ticket.  

Nael Quotes

Stack & Out = Blazing path, lead me to iron rule!
Spread & Dive = Fleeting light! Amid a rain of stars, exalt you the red moon!
Dive & Stack = Fleeting light! 'Neath the red moon, scorch you the earth!
Dive & In = From on high I descend, the hallowed moon to call!
Dive & Out = From on high I descend, the iron path to call!
Dive & Out = From on high I descend, the iron path to walk!
In & Out = O hallowed moon, shine you the iron path!
In & Stack = O hallowed moon, take fire and scorch my foes!
Stack & In = Take fire, O hallowed moon!

Fell Ruin
In & Dive & Spread = From hallowed moon I descend, a rain of stars to bring!
Dive & In & Spread (Missing)

Adds
(Missing All)

**Comment by quisquous** [comment]
Thanks for the report.  Do you have a Network_date.log file you can share with me?

**Comment by dencur** [comment]
The file is too large to attach, I put the zip file here:
[https://file.io/FJffYB](https://file.io/FJffYB)

**Comment by dencur** [comment]
File was too large to upload.  Created a download link here:

https://www.dropbox.com/s/2qu8b2jiao8ivxl/Network_20190701.zip?dl=0

**Comment by dencur** [comment]
Added Nael's mechanic names if it helps.

### Nael Quotes
_Blazing path, lead me to iron rule!_ = Thermionic Beam -> Iron Chariot **(Stack & Out)**
_Fleeting light! Amid a rain of stars, exalt you the red moon!_ = Meteor Stream -> Dalamud Dive **(Spread & Dive)**
_Fleeting light! 'Neath the red moon, scorch you the earth!_ = Dalamud Dive -> Thermionic Beam **(Dive & Stack)**
_From on high I descend, the hallowed moon to call!_ = Raven's Dive -> Lunar Dynamo **(Dive & In)**
_From on high I descend, the iron path to call!_ = Raven's Dive -> Iron Chariot **(Dive & Out)**
_From on high I descend, the iron path to walk!_ = Raven's Dive -> Iron Chariot **(Dive & Out)**
_O hallowed moon, shine you the iron path!_ = Lunar Dynamo -> Iron Chariot **(In & Out)**
_O hallowed moon, take fire and scorch my foes!_ = Lunar Dynamo -> Thermionic Beam **(In & Stack)**
_Take fire, O hallowed moon!_ = Thermionic Beam -> Lunar Dynamo **(Stack & In)**

### Fell Ruin
_From hallowed moon I descend, a rain of stars to bring!_ = Lunar Dynamo -> Raven's Dive -> Meteor Stream **(In & Dive & Spread)**
**(Dive & In & Spread)** Missing

### Adds
(Missing all)

**Comment by quisquous** [comment]
Ok, that should fix everything, theoretically.  (I forgot to tag the dragon issue here, but did commit it in 19fc59bb).

Until I do another release, you can either point your raidboss at https://quisquous.github.io/cactbot/ui/raidboss/raidboss.html or grab https://github.com/quisquous/cactbot/archive/master.zip and copy its ui folder over top of your cactbot ui folder to update with the newest files.

I'm unlikely to go back into ucob any time soon, so let me know if this fixes it or if I broke anything else.

**Comment by dencur** [comment]
Wow that was incredibly fast, just went through, looks great!  You even got the ones I just managed to get from Adds XD.  There was one that was clipped short, but I don't think that it matters, left a comment on the commit.

Thank you so much for what you do!!!

**Comment by dencur** [comment]
Did you also manage to fix the Nael Divebomb markers?

**Comment by quisquous** [comment]
Well, huge shout out to maintenance for giving me three hours to fix some bugs instead of do more main story questing.  \*<_<\*

I'm not 100% sure I fixed divebombs, but I'm pretty sure the capitalization change that I fixed in 19fc59b will do the trick.

**Comment by quisquous** [comment]
Also also, thanks for all the lines.  I pulled the official text from xivapi, but having your explanations for what those meant made it really easy to narrow down the couple that were missing.

**Comment by dencur** [comment]
Awesome, I'll pull master and test it when we go back in tomorrow!

**Comment by quisquous** [comment]
Talking to folks on discord, I think dragons will not work because y and z have been swapped in the position data.  I think the next ffxiv plugin will fix this so I don't want to swap it around only to have it break again.

**Comment by dencur** [comment]
Confirmed today (first time we were able to get back in).  Divebombs are still not working with FFXIV plugin 2.0.2.5.  Attaching logs here:
https://www.dropbox.com/s/fuorns2w87wg7q8/Network_20190708.zip?dl=0

When it calls out A-B-C it says "goto:undefined" and it never calls out the N S E W markers etc.

**Comment by quisquous** [comment]
Hmm, ok.  Thanks for the log.  I'll take a look and see what I can find.  I was hoping that the changes in 2.0.2.5 would get this back to working.

**Comment by dencur** [comment]
Using ACT 3.4.0, with ACTFFXIV Plugin 2.0.2.7 and Cactbot 0.10.2.  Divebombs are not registering, same issue as before.  Also the Doom issue is back.  Link to a clip (You can't see it, but you can hear the doom binging, the screen says "Doom 3, Doom 3, Doom 3, Doom 2, Doom 2, Doom 2, Doom 1, Doom 1" if you have Doom 3.  Maybe the timing needs to be reverted?  

Here is a clip: https://clips.twitch.tv/InterestingSquareGorillaThunBeast

Here is the log.  Thanks! <3
https://www.dropbox.com/s/6jfs4yqlm0en6zp/Network_20190719.zip?dl=0

**Comment by quisquous** [comment]
Sorry for the delay, I was hoping that the changes in the latest plugin would address this, but maybe not.  I'll take a look this weekend and see what I can fix.

**Comment by dencur** [comment]
Thank you!  If you want me to test something before committing, happy to do so.  We're going back in this evening.

**Comment by quisquous** [comment]
Ok, I ran this through the raid emulator with your network log, and I think I got it.  :crossed_fingers: 

Let me know how it goes.  Sorry for the hassle!

**Comment by dencur** [comment]
Thank you so much!  I tested this last night.  Dooms worked great.  It looked like the Nael Markers were right as well (but haven't 100% confirmed since our healer was still remarking XD).  The addon was at least presenting the cardinals correctly.  +1!!!!

**Comment by quisquous** [comment]
Is this all fixed, then? Just curious if there's anything left.

**Comment by dencur** [comment]
It's perfect, thank you for all you do.  Amazing fixes and really fast :).  You're the best.  Closing out.
